// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB4zAoiWpgpgBqmaqG22r2S7vMCgGoDqs',
    appId: '1:183009362941:web:a4b9816976acdc1f878f94',
    messagingSenderId: '183009362941',
    projectId: 'barbearia-tcc',
    authDomain: 'barbearia-tcc.firebaseapp.com',
    databaseURL: 'https://barbearia-tcc-default-rtdb.firebaseio.com',
    storageBucket: 'barbearia-tcc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7InH9JfB-cy-dSPpXea_wMLKObyT0IFo',
    appId: '1:183009362941:android:4dc8162affcf9f30878f94',
    messagingSenderId: '183009362941',
    projectId: 'barbearia-tcc',
    databaseURL: 'https://barbearia-tcc-default-rtdb.firebaseio.com',
    storageBucket: 'barbearia-tcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1O4RKEMAIi6bTJGt8aIksP5s-uAkTLa0',
    appId: '1:183009362941:ios:23c5ef5ab0b7a509878f94',
    messagingSenderId: '183009362941',
    projectId: 'barbearia-tcc',
    databaseURL: 'https://barbearia-tcc-default-rtdb.firebaseio.com',
    storageBucket: 'barbearia-tcc.appspot.com',
    iosBundleId: 'com.example.barbershopSchedule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1O4RKEMAIi6bTJGt8aIksP5s-uAkTLa0',
    appId: '1:183009362941:ios:23c5ef5ab0b7a509878f94',
    messagingSenderId: '183009362941',
    projectId: 'barbearia-tcc',
    databaseURL: 'https://barbearia-tcc-default-rtdb.firebaseio.com',
    storageBucket: 'barbearia-tcc.appspot.com',
    iosBundleId: 'com.example.barbershopSchedule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB4zAoiWpgpgBqmaqG22r2S7vMCgGoDqs',
    appId: '1:183009362941:web:955f66fee3de1058878f94',
    messagingSenderId: '183009362941',
    projectId: 'barbearia-tcc',
    authDomain: 'barbearia-tcc.firebaseapp.com',
    databaseURL: 'https://barbearia-tcc-default-rtdb.firebaseio.com',
    storageBucket: 'barbearia-tcc.appspot.com',
  );
}
